name: moodle_test
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_html: ^0.10.4
  percent_indicator: "^1.0.16"
  crypto: ^2.0.6
  video_player: ^0.10.1+3
  connectivity: ^0.4.6+2
  intl: ^0.15.8
  table_calendar: ^1.2.5
  flutter_widgets: ^0.1.9
  carousel_slider: ^1.4.1
  photo_view: ^0.9.1
  flutter_launcher_icons: ^0.7.4
  flutter_webview_plugin: ^0.3.10+1
  image_downloader: ^0.19.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "images/logo1.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/book_stack.png
    - images/category.png
    - images/learning-wallpaper.png
    - images/loginpic.png
    - images/menu.png
    - images/no_event.png
    - images/placeholder.png
    - images/quiz.png
    - images/sample.jpg
    - images/searchbg.jpg
    - images/topic.png
    - images/wallpaper-1.png
    - images/logo.png
    - images/logo1.png
    - images/logo_splash.png
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.jpg
    - images/7.jpg
    - images/8.jpg
    - images/9.jpg
    - images/10.jpg
    - images/11.jpg
    - images/12.jpg
    - images/13.jpg
    - images/14.jpg
    - images/15.jpg
    - images/16.jpg
    - images/17.jpg
    - images/18.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
